// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhO7wWipuucNaNGwwZyqGHjnjymwtsXdM',
    appId: '1:1009449369695:android:98636241c6e1888f0a5bea',
    messagingSenderId: '1009449369695',
    projectId: 'payflow-7128e',
    storageBucket: 'payflow-7128e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOtm2iOu_xboULfujo8tyVr6CERVWEsBA',
    appId: '1:1009449369695:ios:f186911970e52b1a0a5bea',
    messagingSenderId: '1009449369695',
    projectId: 'payflow-7128e',
    storageBucket: 'payflow-7128e.appspot.com',
    androidClientId: '1009449369695-e0abppidcsqormfou6ld58sr3tq1irbd.apps.googleusercontent.com',
    iosClientId: '1009449369695-4g09rqefn5vv2goabj7stn2hu581s5eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );
}
